[package]
name = "mgl"
version = "0.1.5"
authors = ["phicr"]
edition = "2018"

[dependencies]
pest = "2.1.1"
pest_derive = "2.1.0"
lazy_static = "1.3.0"
clap = "2.33.0"
titlecase = "0.10.0"
mgl_resource_derive = { path = "./mgl_resource_derive" }

